// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbF-7hXpDjRjl5Dz5nOWMnFR0cNXhjjBI',
    appId: '1:154644251886:web:9802978170444126cf1fff',
    messagingSenderId: '154644251886',
    projectId: 'finaltest-1d956',
    authDomain: 'finaltest-1d956.firebaseapp.com',
    storageBucket: 'finaltest-1d956.appspot.com',
    measurementId: 'G-Q7XLGG7TXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoqyPf9ADZLUM0Sv1AMsyN-QHlZ3J-iE',
    appId: '1:154644251886:android:0b8a110bb458d0f6cf1fff',
    messagingSenderId: '154644251886',
    projectId: 'finaltest-1d956',
    storageBucket: 'finaltest-1d956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7y0mXu8IKLqTMabQ8ZS8eMm0z5FjourU',
    appId: '1:154644251886:ios:ebd8c00cb46f331bcf1fff',
    messagingSenderId: '154644251886',
    projectId: 'finaltest-1d956',
    storageBucket: 'finaltest-1d956.appspot.com',
    iosBundleId: 'com.example.tester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7y0mXu8IKLqTMabQ8ZS8eMm0z5FjourU',
    appId: '1:154644251886:ios:fe8c2f060f88dd9fcf1fff',
    messagingSenderId: '154644251886',
    projectId: 'finaltest-1d956',
    storageBucket: 'finaltest-1d956.appspot.com',
    iosBundleId: 'com.example.tester.RunnerTests',
  );
}
